apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=127.0.0.1:8080"
        - "--leader-elect"
        - "--image=$(RELATED_IMAGE_CONTROLLER)"
        - "--namespace=$(TARGET_NAMESPACE)"
        - "--trusted-ca-configmap=$(TRUSTED_CA_CONFIGMAP_NAME)"
        - "--webhook-disable-http2"
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        env:
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /etc/aws-credentials/credentials
          - name: RELATED_IMAGE_CONTROLLER
            # openshift/aws-load-balancer-controller commit: 7d76e6c6d2268bcab6a920ef60594e0c08462532
            # manifest link: https://quay.io/repository/aws-load-balancer-operator/aws-load-balancer-controller/manifest/sha256:41bb8bdcd548a4368bb5e60cd94b2e745e914aabd6c3787a8fc1113fa10f6df8
            value: quay.io/aws-load-balancer-operator/aws-load-balancer-controller@sha256:41bb8bdcd548a4368bb5e60cd94b2e745e914aabd6c3787a8fc1113fa10f6df8
          - name: TARGET_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TRUSTED_CA_CONFIGMAP_NAME
        volumeMounts:
          - mountPath: /etc/aws-credentials
            name: aws-credentials
          - name: bound-sa-token
            mountPath: /var/run/secrets/openshift/serviceaccount
            readOnly: true
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-load-balancer-operator
            items:
              - key: credentials
                path: credentials
        - name: bound-sa-token
          projected:
            defaultMode: 292
            sources:
            - serviceAccountToken:
                audience: openshift
                expirationSeconds: 3600
                path: token
